[package]
name = "isomorphic-server"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
publish = false
edition = "2018"

[dependencies]
actix-web = "0.7.18"
chrono = "0.4.6"
isomorphic-app = { path = "../app" }
env_logger = "0.6.1"
virtual-dom-rs = { path = "../../../crates/virtual-dom-rs" }