[package]
name = "unit-testing-components"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[dependencies]
percy-vdom = { path = "../../crates/percy-vdom" }
