[package]
name = "router-rs-macro"
version = "0.1.0"
authors = ["Chinedu Francis Nwafili <frankie.nwafili@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.27"
quote = "0.6.11"
proc-macro2 = {version = "0.4.27", features = ["nightly"]}
